### ISSUE TITLE
When upgrade set to enabled it DISABLE_AUTO_UPDATE should be set to true

### ISSUE THREAD

**Issue by divansantana** [zanloy/puppet-ohmyzsh#3]
When upgrade enabled for a user like this:

```
# upgrade oh-my-zsh for a single user
ohmyzsh::upgrade { 'user1': }
```

It should then be disabled in the user .zshrc file:
Currently it's set like so:

```
# DISABLE_AUTO_UPDATE="true"
```

Should be:

```
DISABLE_AUTO_UPDATE="false"
```

Otherwise it prompts the user frequently to check for updates even though puppet is managing the updates.

**Comment by zanloy** [comment]
This is fixed by adding an option to ::install instead of ::update (since it's part of .zshrc and thus part of the install to me). You can now use:

``` puppet
class { 'user': disable_auto_update => true }
```

and it should add the following to ~/.zshrc

```
DISABLE_AUTO_UPDATE="true"
```

**Comment by zanloy** [comment]
I also pushed new v1.0.3 to the forge if you are using the forge module.

**Comment by divansantana** [comment]
Awesome - thanks, will try it out! Will be of great use.
